---
# yamllint disable rule:line-length

stages:
  - lint
  - init
  - build

include:
  - project: '$CI_PROJECT_ROOT_NAMESPACE/pipeline-templates'
    ref: main
    file:
      - 'go/lint.yml'
      - 'docker/build-image-ECR.yml'

# Job comming from include build-image-ECR.yml
# Overriding stage config
golangci-lint:
  stage: lint
  # variables:
  #   GOLANGCI_VERSION: "v1.47.1"

ecr_repo_create:
  stage: init

build-image-ECR:
  stage: build
