---
# yamllint disable rule:line-length

stages:
  - code-analysis
  - init
  - build

include:
  - project: '$CI_PROJECT_ROOT_NAMESPACE/pipeline-templates'
    ref: main
    file:
      - 'go/lint.yml'
      - 'go/unitTest.yml'
      - 'docker/ecr.yml'

# Job comming from include build-image-ECR.yml
# Overriding stage config
go_lint_golangci:
  stage: code-analysis

go_unitTest_runTests:
  stage: code-analysis

docker_ecr_repoCreate:
  stage: init

docker_ecr_buildImage:
  stage: build
