---
# yamllint disable rule:line-length

stages:
  - code-analysis
  - code-gating
  - init
  - build

include:
  - project: '$CI_PROJECT_ROOT_NAMESPACE/pipeline-templates'
    # ref: main
    ref: feature/add-ECR-version
    file:
      - 'go/lint.yml'
      - 'go/unitTest.yml'
      - 'docker/ecr.yml'

# Job comming from include build-image-ECR.yml
# Overriding stage config
go_lint_golangci:
  stage: code-analysis

go_unitTest_runTests:
  stage: code-analysis

go_unitTest_codeCoverage:
  stage: code-gating

go_unitTest_gating:
  stage: code-gating
  variables:
    ACCEPTABLE_COVERAGE: 80

docker_ecr_repoCreate:
  stage: init
  only:
    refs:
      - main

docker_ecr_buildImage:
  stage: build
  only:
    refs:
      - main
