---

.install-golangci-lint-script: &install-golangci-lint-script
  - echo "Execute this script second"

stages:
  - lint
  - init
  - build


Golangci-lint:
  stage: lint
  image: golang:1.18-bullseye
  script:
    - *install-golangci-lint-script
    - golangci-lint run --disable structcheck && echo "Success"

Golangci-lint_style:
  stage: lint
  image: golang:1.18-bullseye
  script:
    - *install-golangci-lint-script
    - golangci-lint run --presets style -D interfacer -D golint -D exhaustivestruct -D tparallel -D wastedassign ./...
